// <auto-generated />
namespace VideotheekApp.LIB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class videotheek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(videotheek));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121749308_videotheek"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
