// <auto-generated />
namespace VideotheekApp.LIB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class videotheek6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(videotheek6));
        
        string IMigrationMetadata.Id
        {
            get { return "201712171348186_videotheek6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
